name: Build

on:
  push:
    branches:
      - main
      - rewrite

  pull_request:
    branches:
      - main
      - rewrite

jobs:
  build:
    name: Build
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: 'recursive'

      - name: Set-up MSBuild in PATH
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          msbuild-architecture: x86

      - name: Build
        run: msbuild -m .\Source\slw-dlc-restoration\slw-dlc-restoration.sln

      - uses: actions/upload-artifact@v3.1.3
        with:
          name: my-artifact
          path: Source\slw-dlc-restoration\Build\
